<?xml version="1.0" ?>

<!DOCTYPE config [
  <!ELEMENT config (hub+, ihubpass*)>
  <!ELEMENT hub	(name, cid, maxpacketsize?, 
	startBufferSize?, readSize?, port+, interport*, interconnect*)>
  <!ELEMENT startBufferSize (#PCDATA)>
  <!ELEMENT readSize (#PCDATA)>
  <!ELEMENT maxpacketsize (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT cid (#PCDATA)>
  <!ELEMENT port (#PCDATA)>
  <!ELEMENT interport (#PCDATA)>
  <!ELEMENT interpass (#PCDATA)>
  <!ELEMENT interconnect (host, port)>
  <!ELEMENT host (#PCDATA)>
  <!ELEMENT port (#PCDATA)>
]>

<config>
	<hub>
		<name>-= qhub =-</name>
		<cid>FQI2LLF4K5W3Y</cid>
		<maxpacketsize>65536</maxpacketsize>
		<port>9001</port>
		<!--<port>9002</port>
		<port>9003</port>
		<port>9004</port>-->
		<interport>9000</interport>
		<interpass>majs</interpass>
	</hub>
	<hub>
		<name>skit</name>
		<port>8001</port>
		<cid>THEHUBOFPSEU2</cid>
		<description>Pseu, you da man!</description>
		<interpass>majs</interpass>
		<interconnect>
			<host>localhost</host>
			<port>9000</port>
		</interconnect>
	</hub>
</config>

